services:
  app:
    build: .
    container_name: wb_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "
        composer install &&
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - APP_ENV=local

  db:
    image: mysql:8
    container_name: wb_db
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: wb_sync
        MYSQL_USER: wb_user
        MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  queue:
    container_name: wb_queue
    build: .
    working_dir: /var/www
    command: sh -c "
        echo 'Waiting for DB...' &&
        until php -r '
          try {
            new PDO(\"mysql:host=db;port=3306;dbname=wb_sync\", \"wb_user\", \"secret\");
            echo \"DB connected\n\";
            exit(0);
          } catch (Exception \$e) {
            exit(1);
          }
        '; do
        sleep 2;
        done &&
        php artisan queue:work --tries=3 --timeout=90 --verbose
      "
    restart: always
    volumes:
      - .:/var/www
    depends_on:
      - app
      - db
    environment:
      - APP_ENV=local

volumes:
  db_data:
